# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='banner')),
                ('url', models.URLField(verbose_name='url')),
                ('index', models.IntegerField(default=100, verbose_name='index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'forget')], max_length=5)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'emailVerification',
                'verbose_name_plural': 'emailVerification',
            },
        ),
    ]
