# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170915_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'register'), ('forget', 'forget')], max_length=10),
        ),
    ]
