# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170926_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('Calgary', 'Calgary'), ('Edmonton', 'Edmonton'), ('North', 'North'), ('South', 'South')], default='Edmonton', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Case Worker', 'Case Worker'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Regional Director', 'Regional Director')], default='Case Worker', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
