# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171030_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reportTo',
            field=models.CharField(default='', max_length=30, verbose_name='reportTo'),
        ),
    ]
