# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_reportto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isRegister',
            field=models.BooleanField(default=False),
        ),
    ]
