# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-02 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_isregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_code',
            new_name='postCode',
        ),
    ]
