# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171102_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(default='', max_length=20),
        ),
    ]
