# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171102_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(choices=[('OPG', 'OPG'), ('OPT', 'OPT')], default='OPG', max_length=30, verbose_name='program'),
        ),
    ]
