# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171102_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', 'Case Worker'), ('2', 'Supervisor'), ('3', 'Manager'), ('4', 'Regional Director')], default='Case Worker', max_length=20),
        ),
    ]
