# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20171103_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('Calgary', 'Calgary'), ('Edmonton', 'Edmonton'), ('North', 'North'), ('South', 'South')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Case Worker', 'Case Worker'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Regional Director', 'Regional Director')], max_length=20),
        ),
    ]
