# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20171118_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.CharField(choices=[('Calgary', 'Calgary'), ('Edmonton', 'Edmonton'), ('North', 'North'), ('South', 'South')], default='South', max_length=20),
            preserve_default=False,
        ),
    ]
