# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.CharField(choices=[('Calgary 251', 'Calgary 251'), ('Edmonton 300', 'Edmonton 300'), ('Edmonton 111', 'Edmonton 111'), ('North 92', 'North 92'), ('South 120', 'South 120')], max_length=20),
        ),
    ]
