# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20171220_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Case Worker', 'Case Worker'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Regional Director', 'Regional Director')], default='Supervisor', max_length=20),
        ),
    ]
