# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20171220_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='processStep',
            field=models.CharField(choices=[('Intake', 'Intake'), ('Assessor', 'Assessor'), ('Case Manager', 'Case Manager'), ('Generalist', 'Generalist'), ('Permanenty Worker', '')], default='Intake', max_length=20),
        ),
    ]
