# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knob', models.CharField(max_length=3, verbose_name='knob')),
                ('knob2', models.CharField(max_length=3, verbose_name='knob2')),
                ('knob3', models.CharField(max_length=3, verbose_name='knob3')),
                ('knob4', models.CharField(max_length=3, verbose_name='knob4')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientForm.ClientInfo', verbose_name='clientID')),
            ],
            options={
                'verbose_name': 'CIR',
                'verbose_name_plural': 'CIR',
            },
        ),
    ]
