# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0002_cir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cir',
            name='clientID',
            field=models.CharField(max_length=12, verbose_name='clientID'),
        ),
    ]
