# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0003_auto_20171024_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='status',
            field=models.CharField(choices=[('open and assigned', 'open and assigned'), ('open not assigned', 'open not assigned'), ('onhold', 'onhold'), ('closed', 'closed')], default='open not assigned', max_length=30, verbose_name='status'),
        ),
    ]
