# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-26 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0004_auto_20171026_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CIR',
            new_name='CaseIntensityRating',
        ),
    ]
