# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-30 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0005_auto_20171026_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseintensityrating',
            name='rating',
            field=models.CharField(default='low', max_length=10, verbose_name='rating'),
        ),
    ]
