# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-30 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0006_caseintensityrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='knob',
            field=models.CharField(default='40%', max_length=3, verbose_name='knob'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='knob2',
            field=models.CharField(default='40%', max_length=3, verbose_name='knob2'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='knob3',
            field=models.CharField(default='40%', max_length=3, verbose_name='knob3'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='knob4',
            field=models.CharField(default='40%', max_length=3, verbose_name='knob4'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='rating',
            field=models.CharField(default='low', max_length=10, verbose_name='rating'),
        ),
    ]
