# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-20 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0009_auto_20171118_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='rating',
            field=models.CharField(max_length=10, verbose_name='rating'),
        ),
    ]
