# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientForm', '0010_auto_20171119_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='processStep',
            field=models.CharField(choices=[('Intake', 'Intake'), ('Assessor', 'Assessor'), ('Case Manager', 'Case Manager'), ('Generalist', 'Generalist'), ('Permanenty Worker', '')], default='Intake', max_length=20),
        ),
    ]
